/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Neutre principal — remappé sur la palette KiWee (chaud, quasi-noir) fournie par William.
        // Valeurs pilotées par variables CSS (voir index.css) pour basculer en mode sombre.
        navy: {
          50: 'rgb(var(--color-navy-50) / <alpha-value>)',
          100: 'rgb(var(--color-navy-100) / <alpha-value>)',
          200: 'rgb(var(--color-navy-200) / <alpha-value>)',
          300: 'rgb(var(--color-navy-300) / <alpha-value>)',
          400: 'rgb(var(--color-navy-400) / <alpha-value>)',
          500: 'rgb(var(--color-navy-500) / <alpha-value>)',
          600: 'rgb(var(--color-navy-600) / <alpha-value>)',
          700: 'rgb(var(--color-navy-700) / <alpha-value>)',
          800: 'rgb(var(--color-navy-800) / <alpha-value>)',
          900: 'rgb(var(--color-navy-900) / <alpha-value>)',
          950: 'rgb(var(--color-navy-950) / <alpha-value>)',
        },
        ink: {
          50: '#f5f5f6',
          100: '#e4e4e6',
          200: '#c8c8cc',
          300: '#a0a0a6',
          400: '#8b8e96',
          500: '#5c5f66',
          600: '#3c3c42',
          700: '#2c2f36',
          800: '#1c1e24',
          900: '#16181d',
          950: '#0e0f13',
        },
        // Vert de marque KiWee.
        kiwi: {
          50: '#eaf4f0',
          100: '#d3e5de',
          200: '#a8d4c2',
          300: '#5fae8f',
          400: '#199b78',
          500: '#0d7a5f',
          600: '#0d7a5f',
          700: '#095c47',
          800: '#074a39',
          900: '#063d2f',
          950: '#042920',
        },
        // Ambre/or — gaz, alertes tièdes.
        amber: {
          50: '#fdf9f0',
          100: '#f6efdf',
          200: '#f3e3c8',
          300: '#e0c690',
          400: '#d1a355',
          500: '#b0763c',
          600: '#8a6420',
          700: '#8a5a1c',
          800: '#6f4a17',
          900: '#5c3c1d',
        },
        // Bleu — comptes/immeubles.
        sky: {
          50: '#f0f3f8',
          100: '#eef0f4',
          200: '#d7dde6',
          300: '#a9b8cc',
          400: '#5f7ea3',
          500: '#3b5f8a',
          600: '#2f4d70',
          700: '#243c58',
        },
        // Violet — contacts.
        // LA COULEUR DE L'OPPORTUNITE, relevee dans « Fiche Opportunite.dc.html » (William) :
        // #a8317f pour l'accent, le degrade #8c2168 → #c14e9c pour les pastilles et les boutons,
        // #fdf5fa / #fbeaf4 / #f0cfe3 pour les fonds et bordures claires. Chaque objet du CRM a sa
        // teinte chez William — bleu pour le compte, violet pour le contact, vert pour le site :
        // celle-ci manquait, et la fiche opportunite en etait donc grise.
        opp: {
          50: '#fdf5fa',
          100: '#fbeaf4',
          200: '#f0cfe3',
          300: '#e8c3dc',
          400: '#c14e9c',
          500: '#a8317f',
          600: '#8c2168',
        },
        violet: {
          50: '#f6f2fa',
          100: '#f1edf7',
          200: '#e2d9ef',
          300: '#c3aee0',
          400: '#9a78c4',
          500: '#7c5bb0',
          600: '#63478d',
        },
        // Jetons du handoff design "Fiche Compte" (William, 30/07/2026) — namespace dedie kw.*
        // pour ne pas entrer en collision avec navy/ink/kiwi/amber/sky/violet deja utilises
        // partout ailleurs dans l'app.
        kw: {
          bg: '#f6f6f4',
          surface: '#ffffff',
          subtle: '#fbfbfa',
          muted: '#f0efec',
          sunken: '#f4f3ef',
          border: '#e7e6e2',
          'border-strong': '#e0dfdb',
          'border-subtle': '#f0efec',
          'border-faint': '#f5f4f1',
          ink: '#16181d',
          body: '#3f4249',
          label: '#5c5f66',
          meta: '#83868f',
          faint: '#a3a5a0',
          ghost: '#c0c2bd',
          green: '#0d7a5f',
          'green-dark': '#095c47',
          'green-light': '#eaf4f0',
          'green-border': '#d3e5de',
          'green-tint': '#f4faf7',
          amber: '#b57a24',
          'amber-dark': '#8a6420',
          'amber-light': '#fdf9f0',
          'amber-border': '#f0e4cd',
          gold: '#c8940a',
          'gold-light': '#fdf1c8',
          red: '#c2452d',
          'red-light': '#fbeae5',
          blue: '#3b5f8a',
          'blue-light': '#eef0f4',
          gas: '#4a7fa5',
          'gas-light': '#e9f1f7',
          purple: '#7c5bb0',
        },
      },
      fontFamily: {
        sans: ['"Instrument Sans"', 'system-ui', 'ui-sans-serif', 'sans-serif'],
        display: ['"Instrument Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      backgroundImage: {
        'kiwi-gradient': 'linear-gradient(135deg, #199b78 0%, #0d7a5f 100%)',
        'amber-gradient': 'linear-gradient(135deg, #e0c690 0%, #b0763c 100%)',
        'glow-radial': 'radial-gradient(circle at top left, rgba(13,122,95,0.25), transparent 60%)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        // Un fondu SANS transformation : c'est le voile des fenêtres modales, et une transformation
        // sur lui en ferait le référentiel de ses propres descendants fixed.
        'kw-fade': { from: { opacity: '0' }, to: { opacity: '1' } },
        'kw-fade-slide': { from: { opacity: '0', transform: 'translateY(-6px)' }, to: { opacity: '1', transform: 'none' } },
        'kw-float-up': { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'none' } },
        'kw-slide-in-r': { from: { opacity: '0', transform: 'translateX(46px)' }, to: { opacity: '1', transform: 'none' } },
        'kw-slide-in-l': { from: { opacity: '0', transform: 'translateX(-46px)' }, to: { opacity: '1', transform: 'none' } },
        'kw-bar-grow': { from: { transform: 'scaleX(0)' }, to: { transform: 'scaleX(1)' } },
        'kw-v-grow': { from: { transform: 'scaleY(0)' }, to: { transform: 'scaleY(1)' } },
        'kw-toast-in': { from: { opacity: '0', transform: 'translate(-50%, 8px)' }, to: { opacity: '1', transform: 'translate(-50%, 0)' } },
        'kw-soft-pulse': { '0%, 100%': { boxShadow: '0 0 0 0 rgba(13,122,95,.25)' }, '50%': { boxShadow: '0 0 0 9px rgba(13,122,95,0)' } },
        // Tableau de bord (maquette William, 11/08/2026) : montee des cartes, reflet qui balaie
        // les tuiles d'indicateurs, et pastille « en direct » du fil du portefeuille.
        'kw-card-rise': { from: { opacity: '0', transform: 'translateY(9px)' }, to: { opacity: '1', transform: 'none' } },
        'kw-sheen': { '0%': { transform: 'translateX(-130%) skewX(-18deg)' }, '60%, 100%': { transform: 'translateX(340%) skewX(-18deg)' } },
        'kw-live-pulse': { '0%, 100%': { boxShadow: '0 0 0 3px rgba(13,122,95,.14)' }, '50%': { boxShadow: '0 0 0 5px rgba(13,122,95,.05)' } },
        'kw-hub-pop': { from: { opacity: '0', transform: 'translateY(-7px) scale(.965)' }, to: { opacity: '1', transform: 'none' } },
        'kw-hub-row': { from: { opacity: '0', transform: 'translateX(6px)' }, to: { opacity: '1', transform: 'none' } },
        'kw-hero-rise': { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'none' } },
        'kw-glow-pulse': { '0%, 100%': { opacity: '.42' }, '50%': { opacity: '.72' } },
        // FRISE DE STATUT DE L'OPPORTUNITE (maquette du 23/08/2026). `ringPulse` fait respirer le
        // jalon courant, `stripeMove` fait defiler les hachures du segment qui reste a franchir :
        // c'est ce qui distingue « l'etape en cours » d'une frise inerte.
        'kw-opp-pulse': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(168,49,127,.30)' },
          '50%': { boxShadow: '0 0 0 12px rgba(168,49,127,0)' },
        },
        'kw-stripe': { to: { backgroundPosition: '36px 0' } },
      },
      animation: {
        'fade-up': 'fade-up 0.35s ease-out both',
        'kw-fade': 'kw-fade .12s ease both',
        'kw-fade-slide': 'kw-fade-slide .16s ease both',
        'kw-float-up': 'kw-float-up .16s ease both',
        'kw-slide-in-r': 'kw-slide-in-r .3s cubic-bezier(.3,1.1,.4,1) both',
        'kw-slide-in-l': 'kw-slide-in-l .3s cubic-bezier(.3,1.1,.4,1) both',
        'kw-bar-grow': 'kw-bar-grow .45s cubic-bezier(.3,1.2,.4,1) both',
        'kw-v-grow': 'kw-v-grow .45s cubic-bezier(.3,1.2,.4,1) both',
        'kw-toast-in': 'kw-toast-in .2s ease both',
        'kw-soft-pulse': 'kw-soft-pulse 1.6s ease infinite',
        'kw-card-rise': 'kw-card-rise .4s ease-out both',
        'kw-opp-pulse': 'kw-opp-pulse 2s ease-out infinite',
        'kw-stripe': 'kw-stripe 1.1s linear infinite',
        'kw-sheen': 'kw-sheen 5.5s ease-in-out infinite',
        'kw-hub-pop': 'kw-hub-pop .17s cubic-bezier(.2,.9,.3,1.1) both',
        'kw-hub-row': 'kw-hub-row .2s ease-out both',
        'kw-hero-rise': 'kw-hero-rise .4s cubic-bezier(.3,1.1,.4,1) both',
        'kw-glow-pulse': 'kw-glow-pulse 5s ease-in-out infinite',
        'kw-live-pulse': 'kw-live-pulse 2.2s ease-in-out infinite',
      },
      boxShadow: {
        card: '0 1px 2px 0 rgb(15 23 42 / 0.04), 0 1px 3px 0 rgb(15 23 42 / 0.06)',
        'kw-card': '0 1px 3px rgba(0,0,0,.03)',
        'kw-card-open': '0 3px 10px rgba(0,0,0,.05)',
        'kw-raised': '0 4px 12px rgba(0,0,0,.07)',
        'kw-panel': '0 8px 26px rgba(0,0,0,.13)',
        'kw-overlay': '0 24px 60px rgba(0,0,0,.30)',
        'kw-toast': '0 6px 20px rgba(0,0,0,.25)',
        'kw-green': '0 4px 14px rgba(13,122,95,.32)',
      },
      borderRadius: {
        xl: '0.875rem',
        'kw-xs': '4px', 'kw-sm': '6px', 'kw-md': '8px', 'kw-lg': '9px', 'kw-xl': '11px',
        'kw-2xl': '12px', 'kw-3xl': '14px', 'kw-4xl': '16px', 'kw-5xl': '18px', 'kw-pill': '20px',
      },
      fontSize: {
        'kw-micro': '8.5px', 'kw-tiny': '9px', 'kw-xs': '10px', 'kw-sm': '10.5px', 'kw-base': '11px',
        'kw-md': '11.5px', 'kw-lg': '12px', 'kw-xl': '12.5px', 'kw-h4': '13px', 'kw-h3': '14px',
        'kw-h2': '15px', 'kw-h1': '19px', 'kw-display': '23px',
      },
      spacing: {
        'kw-1': '3px', 'kw-2': '5px', 'kw-3': '6px', 'kw-4': '7px', 'kw-5': '9px', 'kw-6': '11px',
        'kw-7': '12px', 'kw-8': '13px', 'kw-9': '14px', 'kw-10': '15px', 'kw-11': '17px', 'kw-12': '19px',
        'kw-13': '21px', 'kw-14': '22px', 'kw-15': '26px', 'kw-16': '30px',
        'kw-navbar': '56px', 'kw-left-panel': '300px', 'kw-activity-panel': '340px',
        'kw-topbar': '44px', 'kw-tabbar': '38px', 'kw-touch': '44px',
      },
    },
  },
  plugins: [],
}
